### ISSUE TITLE
Add Live Server command

### ISSUE THREAD

**Issue by vitalii-pokrivchak** [csr-tech/csr#1]
### Command
```bash 
csr live --host localhost:8080 --target ./public
```

```bash
csr live -h localhost:8080 -t ./public
```

```bash
# if in config present host and target
csr live
```
### Config for Live Command
```yaml
server:
  host: "localhost:8080"
  target: "./public"
live:
  match: ["./folder/*.js" , "./folder/**"]
```
